# Generated by Django 3.0.5 on 2021-04-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_studentextra_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='status',
        ),
        migrations.AddField(
            model_name='studentextra',
            name='college',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='education',
            field=models.CharField(choices=[('bca', 'BCA'), ('B-TECH', 'BTECH'), ('MCA', 'MCA'), ('M-TECH', 'M-TECH')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='university',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
