# Generated by Django 3.0.5 on 2021-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210418_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
