# Generated by Django 3.0.5 on 2021-04-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210418_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='company_name',
        ),
    ]
