# Generated by Django 3.0.5 on 2021-04-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.TeacherExtra'),
        ),
    ]
