# Generated by Django 3.0.5 on 2021-04-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_job_recruter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
