# Generated by Django 3.0.5 on 2021-04-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_delete_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
