# Generated by Django 3.0.5 on 2021-04-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20210423_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='college_year_of_passing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='hsc_year_of_passing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='school_year_of_passing',
            field=models.IntegerField(null=True),
        ),
    ]
