# Generated by Django 3.0.5 on 2021-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20210423_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='user_image'),
        ),
    ]
