# Generated by Django 3.0.5 on 2021-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_studentextra_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, null=True)),
                ('answer', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
